import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '@/services/api';
import { colors, radii, spacing, typography } from '@/constants/theme';
import { ShopCard } from '@/components/ShopCard';
export default function Explore() { const [open, setOpen] = useState(false); const { data = [] } = useQuery({ queryKey: ['explore', open], queryFn: () => api.shops({ openNow: open }) }); return <SafeAreaView style={styles.safe}><FlatList data={data} keyExtractor={(i) => i.id} contentContainerStyle={styles.content} ListHeaderComponent={<><Text style={styles.title}>Explore</Text><Text style={styles.sub}>The best barbers around you</Text><View style={styles.filters}>{[['Open now', open], ['Earliest', false], ['Nearest', false], ['Price', false]].map(([label, active]) => <Pressable key={String(label)} style={[styles.filter, active && styles.active]} onPress={() => label === 'Open now' && setOpen(!open)}><Text style={[styles.filterText, active && { color: colors.ink }]}>{String(label)}</Text></Pressable>)}</View></>} renderItem={({ item }) => <ShopCard shop={item} onPress={() => router.push({ pathname: '/shop/[id]', params: { id: item.id } })} />} /></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.canvas }, content: { padding: spacing.md, paddingBottom: 120 }, title: { ...typography.display, color: colors.ink }, sub: { ...typography.body, color: colors.muted, marginTop: 3 }, filters: { flexDirection: 'row', gap: 8, marginVertical: spacing.lg }, filter: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: radii.pill, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line }, active: { backgroundColor: colors.lime, borderColor: colors.lime }, filterText: { ...typography.caption, color: colors.muted } });
