import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { api } from '@/services/api';
import { colors, radii, spacing, typography } from '@/constants/theme';
import { ShopCard } from '@/components/ShopCard';
import { SectionTitle } from '@/components/SectionTitle';
export default function Home() { const [query, setQuery] = useState(''); const { data = [], isLoading, refetch, isRefetching } = useQuery({ queryKey: ['shops', query], queryFn: () => api.shops({ query }) }); const asap = useMemo(() => data.filter((s) => s.isOpen && s.nextAvailableAt), [data]); return <SafeAreaView style={styles.safe}><FlatList data={data} keyExtractor={(i) => i.id} refreshControl={<RefreshControl refreshing={isRefetching} onRefresh={refetch} tintColor={colors.ink} />} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.top}><View><Text style={styles.eyebrow}>YOUR CURRENT LOCATION</Text><View style={styles.location}><Ionicons name="location" size={17} color={colors.orange} /><Text style={styles.locationText}>Burdwan, West Bengal</Text><Ionicons name="chevron-down" size={16} color={colors.muted} /></View></View><View style={styles.avatar}><Text style={styles.avatarText}>P</Text></View></View><Text style={styles.greeting}>Where do you want{`\n`}to go today?</Text><View style={styles.search}><Ionicons name="search" size={20} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="Search shops, services, barbers" placeholderTextColor={colors.muted} style={styles.input} returnKeyType="search" /></View><Pressable style={styles.asap} onPress={() => router.push('/explore')}><View style={styles.asapIcon}><Text>⚡</Text></View><View style={{ flex: 1 }}><Text style={styles.asapTitle}>Need a haircut now?</Text><Text style={styles.asapSub}>{asap.length ? `${asap.length} shops available in the next 30 min` : 'Find your next available slot'}</Text></View><Text style={styles.asapArrow}>›</Text></Pressable><SectionTitle title="Quick picks" /><View style={styles.picks}>{['Haircut', 'Beard', 'Hair + Beard'].map((item, i) => <Pressable key={item} style={styles.pick} onPress={() => setQuery(item)}><Text style={styles.pickEmoji}>{['✂️', '🪒', '✨'][i]}</Text><Text style={styles.pickText}>{item}</Text></Pressable>)}</View><SectionTitle title="Nearby shops" action="See all" /></>} ListEmptyComponent={isLoading ? <Text style={styles.empty}>Finding the best cuts near you…</Text> : <Text style={styles.empty}>No barbers nearby yet. Try another search.</Text>} renderItem={({ item }) => <ShopCard shop={item} onPress={() => router.push({ pathname: '/shop/[id]', params: { id: item.id } })} />} />;</SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.canvas }, content: { padding: spacing.md, paddingBottom: 120 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { ...typography.caption, color: colors.muted, fontSize: 10, letterSpacing: 1 }, location: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 }, locationText: { ...typography.body, color: colors.ink, fontWeight: '700' }, avatar: { width: 40, height: 40, borderRadius: 14, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontWeight: '800', color: colors.ink }, greeting: { ...typography.display, color: colors.ink, marginTop: spacing.xl }, search: { backgroundColor: colors.surface, borderRadius: radii.md, height: 54, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', marginTop: spacing.lg }, input: { flex: 1, marginLeft: spacing.sm, color: colors.ink, fontSize: 14 }, asap: { backgroundColor: colors.ink, borderRadius: radii.lg, padding: spacing.md, flexDirection: 'row', alignItems: 'center', marginVertical: spacing.xl }, asapIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center', marginRight: spacing.md }, asapTitle: { color: colors.white, fontSize: 16, fontWeight: '800' }, asapSub: { color: '#C4C7C5', fontSize: 12, marginTop: 4 }, asapArrow: { color: colors.lime, fontSize: 30 }, picks: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.xl }, pick: { flex: 1, backgroundColor: colors.surface, borderRadius: radii.md, paddingVertical: spacing.md, alignItems: 'center' }, pickEmoji: { fontSize: 21, marginBottom: 7 }, pickText: { ...typography.caption, color: colors.ink }, empty: { color: colors.muted, paddingVertical: spacing.xl, textAlign: 'center' } });
