import { useQuery } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { Image } from 'expo-image';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { api } from '@/services/api';
import { type Palette, radii, spacing, typography } from '@/constants/theme';
import { useColors, useThemedStyles } from '@/store/useThemeStore';
import { formatINR } from '@/utils/money';
import { PrimaryButton } from '@/components/PrimaryButton';
export default function ShopDetail() { const colors = useColors(); const styles = useThemedStyles(screenStyles); const { id } = useLocalSearchParams<{ id: string }>(); const { data: shop } = useQuery({ queryKey: ['shop', id], queryFn: () => api.shop(id || '') }); const { data: serviceList = [] } = useQuery({ queryKey: ['services', id], queryFn: () => api.services(id || '') }); if (!shop) return null; return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Image source={shop.imageUrl} style={styles.image} contentFit="cover" /><Pressable style={styles.back} onPress={() => router.back()}><Ionicons name="arrow-back" size={22} color={colors.ink} /></Pressable><Pressable style={styles.heart}><Ionicons name="heart-outline" size={22} color={colors.ink} /></Pressable></View><View style={styles.main}><View style={styles.row}><Text style={styles.title}>{shop.name}</Text><Text style={styles.rating}>★ {shop.rating.toFixed(1)}</Text></View><Text style={styles.meta}>{shop.reviewCount} reviews · {shop.distanceKm.toFixed(1)} km away</Text><Text style={styles.address}>{shop.address}</Text><View style={styles.open}><View style={[styles.dot, { backgroundColor: shop.isOpen ? colors.success : colors.muted }]} /><Text style={{ color: shop.isOpen ? colors.success : colors.muted, fontWeight: '700' }}>{shop.isOpen ? 'Open now' : 'Closed today'}</Text><Text style={styles.hours}> · Closes at 9:00 PM</Text></View><View style={styles.divider} /><Text style={styles.section}>Choose a service</Text>{serviceList.map((service) => <Pressable key={service.id} style={styles.service} onPress={() => router.push({ pathname: '/booking', params: { shopId: shop.id, serviceId: service.id } })}><View style={{ flex: 1 }}><Text style={styles.serviceName}>{service.name}</Text><Text style={styles.duration}>{service.durationMinutes} min · {service.description}</Text></View><Text style={styles.servicePrice}>{formatINR(service.pricePaise)}</Text><Text style={styles.chevron}>›</Text></Pressable>)}<Text style={styles.section}>Why customers come back</Text><View style={styles.tags}>{shop.tags.map((tag) => <Text key={tag} style={styles.tag}>{tag}</Text>)}</View></View></ScrollView><View style={styles.cta}><PrimaryButton label="Book an appointment" onPress={() => router.push({ pathname: '/booking', params: { shopId: shop.id, serviceId: serviceList[0]?.id } })} /></View></SafeAreaView>; }
function screenStyles(colors: Palette) { return StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.canvas }, content: { paddingBottom: 110 }, hero: { height: 255, position: 'relative' }, image: { width: '100%', height: '100%' }, back: { position: 'absolute', top: 12, left: 16, width: 42, height: 42, borderRadius: 14, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, heart: { position: 'absolute', top: 12, right: 16, width: 42, height: 42, borderRadius: 14, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, main: { padding: spacing.md }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: spacing.sm }, title: { ...typography.title, color: colors.ink }, rating: { ...typography.heading, color: colors.ink }, meta: { ...typography.caption, color: colors.muted, marginTop: 5 }, address: { ...typography.body, color: colors.ink, marginTop: spacing.lg }, open: { flexDirection: 'row', alignItems: 'center', marginTop: spacing.sm }, dot: { width: 7, height: 7, borderRadius: 4, marginRight: 6 }, hours: { ...typography.caption, color: colors.muted }, divider: { height: 1, backgroundColor: colors.line, marginVertical: spacing.lg }, section: { ...typography.heading, color: colors.ink, marginBottom: spacing.sm }, service: { backgroundColor: colors.surface, borderRadius: radii.md, padding: spacing.md, flexDirection: 'row', alignItems: 'center', marginBottom: spacing.sm }, serviceName: { ...typography.heading, color: colors.ink }, duration: { ...typography.caption, color: colors.muted, marginTop: 4 }, servicePrice: { ...typography.body, color: colors.ink, fontWeight: '800' }, chevron: { fontSize: 24, color: colors.muted, marginLeft: spacing.sm }, tags: { flexDirection: 'row', gap: 8 }, tag: { ...typography.caption, color: colors.ink, backgroundColor: colors.surface, paddingHorizontal: 12, paddingVertical: 8, borderRadius: radii.pill }, cta: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: spacing.md, backgroundColor: colors.canvas } });
}
